# Introduction to Pandas

Pandas documentation: http://pandas.pydata.org/pandas-docs/stable/ (homepage: https://pandas.pydata.org/)

Notes from Chapter 3 of https://jakevdp.github.io/PythonDataScienceHandbook/

In [2]:
import numpy as np
import pandas as pd
np.__version__, pd.__version__

('1.20.1', '1.2.4')

In [3]:
# show
def show(data, show_data = 0):
    print ("  Type: {:}".format (type(data)))
    print (" Index: {:}".format(data.index))
    if type(data) == pd.core.frame.DataFrame:
        print ("Columns: {:}".format(data.columns))
    print (" Shape: {:}".format(data.shape))
    if show_data:
        print("  Data: {:}".format(data.values))

## Pandas Series Objects

In [5]:
# Create a Pandas Series object - uses the default (implicit) index
d1 = pd.Series([0.25, 0.5, 0.75, 1.0])
show(d1, 1)

  Type: <class 'pandas.core.series.Series'>
 Index: RangeIndex(start=0, stop=4, step=1)
 Shape: (4,)
  Data: [0.25 0.5  0.75 1.  ]


In [6]:
d1

0    0.25
1    0.50
2    0.75
3    1.00
dtype: float64

In [7]:
# So, what exactly is a Pandas Series?
# See the data types for the Series and its components
type(d1), type(d1.values), type(d1.index)

(pandas.core.series.Series,
 numpy.ndarray,
 pandas.core.indexes.range.RangeIndex)

In [ ]:
# What is this pandas.core.series?
dir(pd.core.series)

In [ ]:
# pandas.core indexes?
dir(pd.core.indexes)

In [ ]:
# pandas.core.indexes.range
dir(pd.core.indexes.range)

Note that we did not explicitly define an index -- the index was created implicitly when we created the Series object.

### Series as Generalized NumPy Arrays

In [10]:
# Series as generalized NumPy arrays
# Create the Series with the specfied (explicit) index values
# The "generalization" here is that we are defining a custom index.
d2 = pd.Series([0.25, 0.5, 0.75, 1.0],
               index=['a', 'b', 'c', 'd'])
show(d2, 1)
d2

  Type: <class 'pandas.core.series.Series'>
 Index: Index(['a', 'b', 'c', 'd'], dtype='object')
 Shape: (4,)
  Data: [0.25 0.5  0.75 1.  ]


a    0.25
b    0.50
c    0.75
d    1.00
dtype: float64

In [11]:
d2[3]
# As expected, this is the 4th element, with (implicit) index 3

1.0

In [12]:
# Slicing - Note that element 3 is not inlcuded (as we expect)
d2[1:3]

b    0.50
c    0.75
dtype: float64

In [13]:
# Using the explicit index, we directly access the values using the defined index (similar to a dictionary)
d2['d']

1.0

In [14]:
# Note that element 'c' is included here - More on this below (loc, iloc)
d2['b':'c']

b    0.50
c    0.75
dtype: float64

In [15]:
# Note that the indices don't have to be numerical or "alphabetic" in the sequence-sense
pets = pd.Series(['dog', 'cat', 'fish', 'hamster'],
               index=['best', 'worst', 'useless', 'why'])
show(pets, 1)
pets

  Type: <class 'pandas.core.series.Series'>
 Index: Index(['best', 'worst', 'useless', 'why'], dtype='object')
 Shape: (4,)
  Data: ['dog' 'cat' 'fish' 'hamster']


best           dog
worst          cat
useless       fish
why        hamster
dtype: object

In [16]:
# access single object
pets['useless'], type(pets['useless'])

('fish', str)

In [17]:
# slice
pets['useless':]

useless       fish
why        hamster
dtype: object

In [18]:
type(pets['useless':])

pandas.core.series.Series

In [19]:
pets['best':'useless']

best        dog
worst       cat
useless    fish
dtype: object

### Series as Generalized Python Dictionaries

In [20]:
# Creating a Series from a dictionary - keys -> Index; values -> Values.  
# Note that that Pandas object used to sort the series using the dictionary key sort order.
# As of version 0.23 -- it now maintains the order specified in the
# dict defintion -- see the documentation for details)
population_dict = {'California': 38332521,
                   'Texas'     : 26448193,
                   'New York'  : 19651127,
                   'Florida'   : 19552860,
                   'Illinois'  : 12882135}
population = pd.Series(population_dict)
show(population, 1)
population

  Type: <class 'pandas.core.series.Series'>
 Index: Index(['California', 'Texas', 'New York', 'Florida', 'Illinois'], dtype='object')
 Shape: (5,)
  Data: [38332521 26448193 19651127 19552860 12882135]


California    38332521
Texas         26448193
New York      19651127
Florida       19552860
Illinois      12882135
dtype: int64

In [22]:
# Note again that the Pandas object no longer stores in sort order.
sorted(population_dict.keys())

['California', 'Florida', 'Illinois', 'New York', 'Texas']

In [23]:
# Looks like a dictionary ....
population['Illinois']

12882135

In [24]:
# but with list-like slicing
population['Florida':'Illinois']

Florida     19552860
Illinois    12882135
dtype: int64

In [25]:
# along with "regular" slicing
population[3:5]

Florida     19552860
Illinois    12882135
dtype: int64

In [26]:
area_dict = {'California': 423967, 'Texas': 695662, 'New York': 141297,
             'Florida': 170312, 'Illinois': 149995}
area = pd.Series(area_dict)
show(area,1)
area

  Type: <class 'pandas.core.series.Series'>
 Index: Index(['California', 'Texas', 'New York', 'Florida', 'Illinois'], dtype='object')
 Shape: (5,)
  Data: [423967 695662 141297 170312 149995]


California    423967
Texas         695662
New York      141297
Florida       170312
Illinois      149995
dtype: int64

In [27]:
# So, now we have two series that use the same index for different categories
# of values (population, area)
print("{:}\n\n{:}".format(population, area))
# Hopefully the direction is clear --> let's combine these using meaningful names.

California    38332521
Texas         26448193
New York      19651127
Florida       19552860
Illinois      12882135
dtype: int64

California    423967
Texas         695662
New York      141297
Florida       170312
Illinois      149995
dtype: int64


## Pandas DataFrame Objects

In [29]:
# DataFrame is the ticket
states = pd.DataFrame({'population': population,'area': area})
show(states,1)

  Type: <class 'pandas.core.frame.DataFrame'>
 Index: Index(['California', 'Texas', 'New York', 'Florida', 'Illinois'], dtype='object')
Columns: Index(['population', 'area'], dtype='object')
 Shape: (5, 2)
  Data: [[38332521   423967]
 [26448193   695662]
 [19651127   141297]
 [19552860   170312]
 [12882135   149995]]


In [31]:
# Or in a user-friendly display
states

population    area
California    38332521  423967
Texas         26448193  695662
New York      19651127  141297
Florida       19552860  170312
Illinois      12882135  149995

In [32]:
# Closer look at the DataFrame components and respective data types
states.index

Index(['California', 'Texas', 'New York', 'Florida', 'Illinois'], dtype='object')

In [33]:
states.columns

Index(['population', 'area'], dtype='object')

In [34]:
states.values

array([[38332521,   423967],
       [26448193,   695662],
       [19651127,   141297],
       [19552860,   170312],
       [12882135,   149995]], dtype=int64)

In [35]:
type(states), type(states.index), type(states.columns), type(states.values)
# Note here that both the index and the column sequence are defined as index objects

(pandas.core.frame.DataFrame,
 pandas.core.indexes.base.Index,
 pandas.core.indexes.base.Index,
 numpy.ndarray)

In [36]:
# extract one of the two Series using its column name
states['area']

California    423967
Texas         695662
New York      141297
Florida       170312
Illinois      149995
Name: area, dtype: int64

In [37]:
# now the other Series ...
states['population']

California    38332521
Texas         26448193
New York      19651127
Florida       19552860
Illinois      12882135
Name: population, dtype: int64

In [38]:
# and the respective types
type(states), type(states['area']), type(states['population'])

(pandas.core.frame.DataFrame,
 pandas.core.series.Series,
 pandas.core.series.Series)

In [39]:
# let's add another colum -- this time of non-numeric data
color_dict = {'California': 'blue', 'Texas': 'red', 'New York': 'blue',
             'Florida': 'purple', 'Illinois': 'purple'}
color = pd.Series(color_dict)
show(color,1)
color

  Type: <class 'pandas.core.series.Series'>
 Index: Index(['California', 'Texas', 'New York', 'Florida', 'Illinois'], dtype='object')
 Shape: (5,)
  Data: ['blue' 'red' 'blue' 'purple' 'purple']


California      blue
Texas            red
New York        blue
Florida       purple
Illinois      purple
dtype: object

In [43]:
# add our new column to the DataFrame
states['color'] = color.values
show(states,1)

  Type: <class 'pandas.core.frame.DataFrame'>
 Index: Index(['California', 'Texas', 'New York', 'Florida', 'Illinois'], dtype='object')
Columns: Index(['population', 'area', 'color'], dtype='object')
 Shape: (5, 3)
  Data: [[38332521 423967 'blue']
 [26448193 695662 'red']
 [19651127 141297 'blue']
 [19552860 170312 'purple']
 [12882135 149995 'purple']]


In [42]:
# user-friendly form
states

population    area   color
California    38332521  423967    blue
Texas         26448193  695662     red
New York      19651127  141297    blue
Florida       19552860  170312  purple
Illinois      12882135  149995  purple

In [41]:
# since NumPy arrays are homogeneous, the values array is now of type 'object'
states.values, type(states.values)

(array([[38332521, 423967, 'blue'],
        [26448193, 695662, 'red'],
        [19651127, 141297, 'blue'],
        [19552860, 170312, 'purple'],
        [12882135, 149995, 'purple']], dtype=object),
 numpy.ndarray)

In [44]:
# but the individual series datatypes reflect the series data types.
states['area'].values, states['population'].values, states['color'].values

(array([423967, 695662, 141297, 170312, 149995], dtype=int64),
 array([38332521, 26448193, 19651127, 19552860, 12882135], dtype=int64),
 array(['blue', 'red', 'blue', 'purple', 'purple'], dtype=object))

## Pandas Index Objects

From VP 03.01 - "The index object ... can be thought of as an immutable array or an ordered set (technically as a multi-set, as Index objects can have repeat values).

In [ ]:
ind1 = states.index
ind1, type(ind1)

In [ ]:
# Array-type operations
ind1[2:]

In [ ]:
ind1[-2:]

In [ ]:
ind1[::2]

In [ ]:
# immutable
ind1[1] = 'Alabama'

In [ ]:
# Set operations -- union, intersection, etc.
indA = pd.Index([1, 3, 5, 7, 9])
indB = pd.Index([2, 3, 5, 7, 11])

In [ ]:
indA & indB  # intersection

In [ ]:
indA | indB  # union

In [ ]:
indA ^ indB  # symmetric difference

## Indexers - loc, iloc, and (what used to be) ix

In [ ]:
# Consider this example from VanderPlas
data = pd.Series(['a', 'b', 'c', 'd'], index=[1, 3, 5, 7])
show(data)
data

In [ ]:
# Explicit index - note that with a zero-based indexing, we 
# would expect the second element of the list.
data[1]

In [ ]:
# Implicit indexing when slicing - now we get the second and third 
# elements.
data[1:3]

This can cause confusion -- when is explicit indexing used and when is implicit indexing used ... Hence, loc and iloc.

In [ ]:
# loc - always uses the explicit index 
data.loc[1]

In [ ]:
data.loc[1:3]

In [ ]:
# iloc - always uses the implicit Python-style index
data.iloc[1]

In [ ]:
data.iloc[1:3]

In [ ]:
# Note that even with non-integer indexes the slicing behavior is still different
data1 = pd.Series(['a', 'b', 'c', 'd'], index=['h','i','j','k'])
data1

In [ ]:
data1[1:3]

In [ ]:
data1.iloc[1:3]

In [ ]:
data1.loc['i':'k']

## Data selection in a DataFrame

In [ ]:
# Recreate our states DataFrame ...
area = pd.Series({'California': 423967, 'Texas': 695662,
                  'New York': 141297, 'Florida': 170312,
                  'Illinois': 149995})
pop = pd.Series({'California': 38332521, 'Texas': 26448193,
                 'New York': 19651127, 'Florida': 19552860,
                 'Illinois': 12882135})
color = pd.Series({'California': 'blue', 'Texas': 'red',
                 'New York': 'blue', 'Florida': 'red',
                 'Illinois': 'purple'})
data = pd.DataFrame({'area':area, 'pop':pop, 'color':color})
show(data)
data

In [ ]:
# dictionary style indexing -- picking columns
data['area']

In [ ]:
# works in cases where column names are character-based and
# are not reserve works
data.area

In [ ]:
# lists of columns -- note that you can specify the order and note
# the double brackets.
data[['pop', 'area']]

In [ ]:
# Add a new series using existing series
data['density'] = data['pop'] / data['area']
data
# Note the ufunc (universal function) behavior

In [ ]:
# loc and iloc do element selection and slicing (rows)
data.iloc[1,2]

In [ ]:
data.iloc[:3, :2]

In [ ]:
data.iloc[1:3]

In [ ]:
# Oops -- not using numerical index!
data.loc[1:3]

In [ ]:
# Notice that this slice includes the "ending row" where the
# iloc-based slicing did not (it used standard Python slicing)
data.loc['Texas':'Florida']

In [ ]:
# Masking
data[data.density > 100]
# what does 'data.density > 100' return (it's an expression that
# is evaluated)?

In [ ]:
# when in doubt, check it out!
data.density > 100

In [ ]:
data[(data.density > 100) & (data.area < 150000)]

In [ ]:
# Masking + column selection
data.loc[data.density > 100, ['color', 'density']]

In [ ]:
# let's look at the object
type(data.loc[data.density > 100, ['color', 'density']])

In [ ]:
# lets create a named slice
high_density = data.loc[data.density > 100, ['color', 'density']]
high_density

In [ ]:
# and change something
high_density.iloc[0,0] = "purple"
high_density

In [ ]:
# what about the original?
data

Hmmmm ... So the slice is a copy and not a view.  What are the rules here (for Pandas slices)?
https://stackoverflow.com/questions/23296282/what-rules-does-pandas-use-to-generate-a-view-vs-a-copy

## See Sample Data Indexing and Selection Examples Notebook

## Handling Missing Data

In [ ]:
data = pd.Series([1, np.nan, 'hello', None])
show(data)
data

In [ ]:
data.isnull()

In [ ]:
# masking
data[data.notnull()]

In [ ]:
# remove the missing data elements
data.dropna()

In [ ]:
# dropna() created a new Series object -- the original is unchanged
data